### PR TITLE
Fix issue with not being able to remove channel avatar or cover

### LINKED ISSUE #3357: Removing channel cover and/or channel avatar is not working
To reproduce
1. Have a channel with a cover set. 
2. Update this cover(to enable the delete button)
3. Click cover again to delete it
4. Click publish changes 
5. Wait until the transaction ends
6. Refresh the site
7. The cover is still set

The same applies to avatars, unfortunately. It looks like we're passing some wrong values when sending transactions.

### PR DESCRIPTION
**Pull request by drillprop**
Fix #3357

### CODE REVIEW

**Review by rafalpawlow — CHANGES_REQUESTED** [review]
Something is wrong.

1. Delete avatar and sign transaction
2. Upload new one
3. Sign transaction
4. Refresh page
5. No avatar

**Comment by drillprop** [comment]
> Something is wrong.
> 
> 1. Delete avatar and sign transaction
> 2. Upload new one
> 3. Sign transaction
> 4. Refresh page
> 5. No avatar

I can't reproduce it, works for me

**Comment by rafalpawlow** [comment]
@drillprop take a look

https://user-images.githubusercontent.com/13706246/198247503-a5d6560a-cc7e-435d-bc75-2d21767af3ed.mov

**Comment by drillprop** [comment]
> @drillprop take a look
> 
>  Nagranie.z.ekranu.2022-10-27.o.11.24.57.mov

Because you refresh the site while the image is still processing, it's not available(it's actually not there yet for a few seconds)
image
How should I suppose to fix that?

**Comment by rafalpawlow** [comment]
Of course, you are right 🤦. I don't think it's an issue

**Review by rafalpawlow — APPROVED** [review]

**Pull request merged**
