### PR TITLE
upgrade deps, use Vite v3

### PR DESCRIPTION
**Pull request by kdembler**

### CODE REVIEW

**Review by rafalpawlow — CHANGES_REQUESTED** [review]
I see this error in Webstorm
https://stackoverflow.com/questions/73509984/eslint-typeerror-this-liboptions-parse-is-not-a-function

Zrzut ekranu 2022-09-8 o 13 50 05

**Comment by kdembler** [comment]
It's a Webstorm issue, but okay, pinned eslint to 8.22 for now

**Review by drillprop — CHANGES_REQUESTED** [review]
The error `document is not defined` is back. With this error, we won't be able to send transactions at all on production/deployment.
image

I don't remember how I fixed this before, I think I did some patching, but not super sure.

**Comment by drillprop** [comment]
https://github.com/Joystream/atlas/pull/3065 I fixed this here

**Comment by kdembler** [comment]
Fixed

**Review by rafalpawlow — APPROVED** [review]

**Review by drillprop — APPROVED** [review]

**Pull request merged**
