### PR TITLE
Action bar updates

### PR DESCRIPTION
**Pull request by eldiegod**
fixes: #2775

### CODE REVIEW

**Review by rafalpawlow — CHANGES_REQUESTED** [review]
Horizontal padding is wrong, from SM to MD it should be `16px`

**Review by rafalpawlow — CHANGES_REQUESTED** [review]
I cannot see this text in storybook, is it implemented in the component?
Zrzut ekranu 2022-06-14 o 15 08 03

**Comment by eldiegod** [comment]
> I cannot see this text in storybook, is it implemented in the component?



> I cannot see this text in storybook, is it implemented in the component? Zrzut ekranu 2022-06-14 o 15 08 03

@rafalpawlow yes, you just have to be at the right breakpoint (LG)

**Comment by rafalpawlow** [comment]
@eldiegod  Right 🤦. LGTM but let's do the rebase and be sure everything is fine

**Review by rafalpawlow — CHANGES_REQUESTED** [review]
Sorry I found one more thing. Spacing between primary button and badge is wrong, it's `32px` and should be `16px`. I think because of lack of secondary button, gap is doubled.
Zrzut ekranu 2022-06-14 o 22 22 43

Also I'm not sure about padding in badge, as you can see it should be `8px` but in your implementation padding is `16px`
Zrzut ekranu 2022-06-14 o 22 23 40

**Comment by toiletgranny** [comment]
Should I be taking a look at this as well?

**Comment by eldiegod** [comment]
> Should I be taking a look at this as well?

@toiletgranny Ideally, but storybooks in the PRs are sadly not working for the time being 😔

**Comment by eldiegod** [comment]
> Sorry I found one more thing. Spacing between primary button and badge is wrong, it's `32px` and should be `16px`. I think because of lack of secondary button, gap is doubled. Zrzut ekranu 2022-06-14 o 22 22 43
> 
> Also I'm not sure about padding in badge, as you can see it should be `8px` but in your implementation padding is `16px` Zrzut ekranu 2022-06-14 o 22 23 40

@rafalpawlow how did you get that double gap applied? for me when I remove secondary button it just works as expected.

also left the padding of the badge at 12px for md up because it looks a bit better when hovered

**Comment by eldiegod** [comment]
@toiletgranny nvm it works now, feel free to give it a go

**Comment by rafalpawlow** [comment]
@eldiegod this screenshot comes from video workspace

**Comment by eldiegod** [comment]
> @eldiegod this screenshot comes from video workspace

@rafalpawlow ah yes, I didn't notice a tooltip was added to the primary button and it messed the styles.
Spacing should be good now

**Review by rafalpawlow — APPROVED** [review]

**Comment by toiletgranny** [comment]
@eldiegod, @kdembler asked me to let you know that we've just introduced a new set of changes to the Action bar component, that Klaudiusz would like to be included in the scope of this PR. All you need to know can be found in the newest changelog entry in Figma, [under this link](https://www.figma.com/file/Pf31tuYpozYmpq163U2ho8/Web-components?node-id=7688%3A149633) (the link points directly to the newest changelog entry).

image

⚠️ Please note that the fee information should be now displayed in all instances of the Action bar component, which includes flows such as the NFT listing (currently, the implementation disregards the designs and omits this information in the Action bar component), or the NFT purchase view.

**Review by kdembler — CHANGES_REQUESTED** [review]
I've noticed that there is no "Cancel" button when editing a video now

**Review by toiletgranny — CHANGES_REQUESTED** [review]
These changes look great! Apart from the missing secondary button in video & NFT workspaces, which @kdembler already pointed out, there's one item in the changelog, which seems to be overlooked, and it is:
> Replaced the local “Draft info” component with a string and the Information component

Basically, the idea is to replace the "Drafts are saved automatically" info, with a standard line of text and an instance of the Information component next to it. Also, please note that the contents of the tooltip, as well as the caption next to it, should now be customizable in different instances of the Action bar component. :)

**Comment by toiletgranny** [comment]
I was unclear with my prev comment, sorry! 😅

The lorem ipsum part is now correct, but, additionally, the ask was to replace this part:
CleanShot 2022-06-21 at 14 42 12
with this:
CleanShot 2022-06-21 at 14 43 52

So, in other words, to replace whatever is currently used for displaying that tooltip and the rectangle around it the "Lorem ipsum (i)" with a raw piece of text and the [Information component](https://www.figma.com/file/Pf31tuYpozYmpq163U2ho8/Web-components?node-id=6215%3A141264).

---

While we're on the subject of the Tooltip component, @kdembler brought my attention to the fact that the current documentation for this component does not match the designs provided in Figma and is in contradiction with its other parts, for which I apologize. 

I was thinking, could we use this opportunity and this PR, to change our approach to defining the tooltip width? For the implementation to remain truthful the initial designs, I would recommend dropping the `max-width`declaration from the tooltip, as a container, and reapplying it to the `<span>` element with the tooltip's body text, with the value of `200px`. Using the CSS class names I found in Chrome dev tools in the above deployment, the CSS changes would literally translate to something as simple as this:
```css
.css-1wdn4wd {
   [...]
    /* max-width: 224px; */
   [...]
}
```

```css
.css-xrxhyo {
    [...]
    max-width: 200px;
}
```

Could we do that? Please, let me know, and if that's a 🟢 from you guys, then I'm updating docs in Figma.

**Review by kdembler — APPROVED** [review]

**Pull request merged**
