### PR TITLE
Scrollbar styles

### PR DESCRIPTION
**Pull request by eldiegod**
Scrollbar styles for firefox and webkit browsers
https://www.figma.com/file/rBjfm2tJ2Pr9M0UNTduU9v/Joystream-Atlas?node-id=7465%3A195160

### CODE REVIEW

**Comment by mikkio-j** [comment]
Looks good! In firefox it seems like there is full coverage for all scrollbars, but in Chromium-based browsers I miss styles in following places:

- followed channels list in viewer's sidenav
- channels list in studio's topbar dropdown
- select input
- video sheet form

**Comment by eldiegod** [comment]
The chrome issues should be fixed in the last commit

**Review by drillprop — COMMENTED** [review]
Tested on chrome and firefox. Works on chrome, but on firefox, I see just a regular one - is it intentional or I missing something? 
Tested it on mac, btw.

**Review by drillprop — APPROVED** [review]
> Tested on chrome and firefox. Works on chrome, but on firefox, I see just a regular one - is it intentional or I missing something?
> Tested it on mac, btw.

I think we can ignore this. Turns out that it works well, but you have to enable the option `show scrollbar: always` on mac preferences.

**Review by mikkio-j — APPROVED** [review]

**Review by kdembler — APPROVED** [review]

**Pull request merged**
