### PR TITLE
Create Video file encoding.md

### PR DESCRIPTION
**Pull request by KubaMikolajczyk**
Started a new docs for video file encoding

### CODE REVIEW

**Review by kdembler — COMMENTED** [review]
I like the idea of creating this document, however I'm not sure how true this data is. First off, it's likely not enough to mention the browser name, it also depends on its version, but I guess we could assume "latest". Second off, the data doesn't seem to be fully truthful, Safari supports WebM and VP8/9 for some time now.

**Comment by drillprop** [comment]
I think the most accurate data about browser support should be here: https://developer.mozilla.org/en-US/docs/Web/Media/Formats/Video_codecs 

[This](https://videojs.com/html5-video-support/)  also could be helpful

**Comment by KubaMikolajczyk** [comment]
> I like the idea of creating this document, however I'm not sure how true this data is. First off, it's likely not enough to mention the browser name, it also depends on its version, but I guess we could assume "latest". Second off, the data doesn't seem to be fully truthful, Safari supports WebM and VP8/9 for some time now.

@kdembler Yes it might not be accurate - I will update it with the examples from @drillprop 


> I think the most accurate data about browser support should be here: https://developer.mozilla.org/en-US/docs/Web/Media/Formats/Video_codecs
> 
> [This](https://videojs.com/html5-video-support/) also could be helpful

The table from video js about supported codecs is awesome - we can include it here - do you know any simmilar resources about video formats (I think we should include that as well in separate table except the codecs, or am I wrong and there is a better way to describe which formats are accepted?)

**Comment by kdembler** [comment]
That resource from MDN looks great but I think it's not fully up to date as well, as it mentions Safari not supporting VP8/VP9 but it does :P I'm wondering whether we actually need a table like this. After all, users don't want to upload a video that works only for their browser, they want to upload files that will be playable by all users. Maybe instead of this doc we just condense this knowledge and place it directly in the file picker? We could just suggest using `MP4/H.264` or `WEBM/VP8,VP9` and call it a day?

**Comment by KubaMikolajczyk** [comment]
> That resource from MDN looks great but I think it's not fully up to date as well, as it mentions Safari not supporting VP8/VP9 but it does :P I'm wondering whether we actually need a table like this. After all, users don't want to upload a video that works only for their browser, they want to upload files that will be playable by all users. Maybe instead of this doc we just condense this knowledge and place it directly in the file picker? We could just suggest using `MP4/H.264` or `WEBM/VP8,VP9` and call it a day?

Alright this sounds okish :) at least we would inform about possibilities right away - do you have any suggestions for the image file extensions of thumbnails as well to make it consistent?

**Comment by kdembler** [comment]
For images JPEG and WEBP should be good

**Comment by KubaMikolajczyk** [comment]
OK so Im closing this and deleting the branch we will use this solution!

**Pull request closed without merging**
