### PR TITLE
Payments table component

### LINKED ISSUE #3417: Create payments table component
## Context
Originating Epic

* https://github.com/Joystream/atlas/issues/2401

## Design
Link to Figma > [LINK](https://www.figma.com/file/ZFRXsyGvnBXnkDUUGc5vyR/My-payments?node-id=1552%3A80425)

## Scope
* [ ] Table with:
	* [ ] Date 
	* [ ] Type of Transaction (NFT sale, NFT royalties, Council Reward Claimed, Withdrawal, (in the future) YPP reward)
	* [ ] Amount 
	* [ ] Channel Balance (nice to have, we can skip initially)
* [ ] Simulate client-side pagination
* [ ] Mock local data just for component work

## Out of scope

- [ ] Fetching the data

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202078489349362/1203312862107007) by [Unito](https://www.unito.io)
┆Link To Task: https://app.asana.com/0/1202078489349362/1203312862107007

### PR DESCRIPTION
**Pull request by rafalpawlow**
Closes #3417 

**Design**
https://www.figma.com/file/ZFRXsyGvnBXnkDUUGc5vyR/My-payments?node-id=1552%3A80425

### CODE REVIEW

**Comment by drillprop** [comment]
@rafalpawlow just out of curiosity  - why didn't you use @tanstack/react-table? Why did you pick the older version?

**Comment by rafalpawlow** [comment]
@drillprop I didn't notice there is a newer version, my bad!

**Comment by drillprop** [comment]
> @drillprop I didn't notice there is a newer version, my bad!

hmm, that's ok, I thought there was some reason behind this. We'll think about migrating.

**Comment by kdembler** [comment]
@drillprop Will you be reviewing this PR?

**Review by drillprop — APPROVED** [review]

**Pull request merged**
