### PR TITLE
Video and NFT form update

### LINKED ISSUE #2738: Update the video upload form
The goal of this task is to update the entire Video upload form in the Video workspace view so that it's aligned with the new form guidelines.

### PR DESCRIPTION
**Pull request by drillprop**
Fix #2738
Desings: https://www.figma.com/file/xm6vBdSnQDroc57rGfGtPM/Video-workspace?node-id=1378%3A93428

### CODE REVIEW

**Review by toiletgranny — CHANGES_REQUESTED** [review]
It's so satisfying to see all the pieces coming together! Thanks, @drillprop, for making my day a lot better! ❤️ As this task was especially challenging in capturing all the details that have changed, the list of findings below might seem rather long, but — hopefully — most of them are simple and quick fixes, like typos, or margins.

### Video workspace

1. After initial unsuccessful validation, the Title input component doesn't turn its styling back to the default one upon providing a valid input. It should.
2. Licenses listed in the Select component don't feature their full names displayed as Caption of the List Item component. [Please, see the designs here.](https://www.figma.com/file/xm6vBdSnQDroc57rGfGtPM/Video-workspace?node-id=3151%3A197245)
3. The Custom license field comes with a wrong placeholder; it should say "Describe your custom license  ".
4. I was able to send a form with a Custom license field being empty. I should not. It becomes mandatory if my License selection is set to Custom.
5. The "Show locked options" section in the Edit video form, with the NFT being issued on a video, is mixed up: there are duplicated fields, there is no bottom padding underneath.
6. Deleting a video brings up an incorrect type of the Alert dialog component: Warning. It should be set to: Destructive.
7. Discarding changes in the video information in the Edit mode doesn't trigger the Alert dialog. It should. [Please, see the designs.](https://www.figma.com/file/xm6vBdSnQDroc57rGfGtPM/Video-workspace?node-id=3165%3A165937)
8. Hovering over uploaded video thumbnail doesn't display an overlay, [as specified in the designs](https://www.figma.com/file/xm6vBdSnQDroc57rGfGtPM/Video-workspace?node-id=3170%3A167108). Could it be that the Dropzone, or File select components implementation doesn't support it? 
9. Distance between the FIle select component and the rest of the form is too large on the XXS breakpoint. It should be set to `48px`. 
10. Padding around the form is set incorrectly on the MD breakpoint and going forwards. It's set to `48px` on top and `32px` on the sides, whereas it should be set to `48px` on all sides. [Please, see the designs.](https://www.figma.com/file/xm6vBdSnQDroc57rGfGtPM/Video-workspace?node-id=3228%3A1537701). Also, the`max-width` is calculated incorrectly; please see the designs for the XL breakpoint and inspect the width of each of the columns, while comparing it to the width in the implementation.
11. In general, validation messages do not match the designs and the new form guidelines. Validation messages for the Video workspace [can be found here](https://www.figma.com/file/xm6vBdSnQDroc57rGfGtPM/Video-workspace?node-id=3171%3A166595).


### NFT workspace
1. In general, the RWD implementation is off compared to the [Figma designs](https://www.figma.com/file/xm6vBdSnQDroc57rGfGtPM/Video-workspace?node-id=3231%3A147893). Here are the things to watch out for:
    - The NFT preview visibility on smaller breakpoints,
    - Left & right padding on smaller breakpoints,
    - Clipping and visibility of the horizontally scrolled Stepper component,
    -  The`max-width` property set on the form contents.
2. The "Your NFT preview" section is off compared to the designs. Please note the "Your NFT preview" label has been dropped, and that, currently, the NFT tile component is not centered vertically in the implementation (it should be).
3. There's a missing comma in the "Choose how you want to sale your NFT." sentence in the first step.
4. In the Auction listing type, the "Minimum bid" should be enabled by default. Currently, it's not.
5. It seems like "Minimum bid" "Buy now price", or "Whitelist" fields are being validated on every keystroke, or every change. A reminder we agreed to do that on blur. This doesn't create a pleasant UX, especially with fields such as the Whitelist, which always punishes me, as the user, after adding the first member to the whitelist. Can we change the validation, so that it matches global guidelines?
   - Also, having added 2 members into my Whitelist, removing one triggers validation instantly. Instead, can we validate this field upon hitting the "Next step" button? 🙏 
7. Enabling the "Buy now price" having typed something else than `1` into the "Minimum bid" always causes the "Minimum bid" field to be validated as incorrect, as the "Buy now price" default value is set to `2`. This is not a pleasant UX. Instead, upon first enabling of the "Buy now price" field, can we have its value being prepopulated with a number, which is higher than the **current** "Minimum bid" value by one? 🙏 
8. The "Next step" button remains disabled until all fields match validation criteria. A reminder that, according to the new form guidelines, it shouldn't be disabled. Clicking it should validate the form.
9. Please, make sure all validation messages end with a dot so that we're aligned with the new form guidelines.
10. The "Go back" button in the footer should be labeled as "Back".
11. Closing the NFT workspace while being at step 2 or 3 doesn't trigger the Alert dialog. It should. [Please, see the designs.](https://www.figma.com/file/xm6vBdSnQDroc57rGfGtPM/Video-workspace?node-id=2393%3A80584)


Side note: Is that [number formatting in inputs](https://www.figma.com/file/Pf31tuYpozYmpq163U2ho8/Web-components?node-id=7479%3A153884) something that's still on our radar? Asking as it's not implemented yet, and I remember at some point you guys told me it will be implemented soon, in some other issue. 😅 (cc @kdembler)

**Comment by kdembler** [comment]
> Side note: Is that [number formatting in inputs](https://www.figma.com/file/Pf31tuYpozYmpq163U2ho8/Web-components?node-id=7479%3A153884) something that's still on our radar? Asking as it's not implemented yet, and I remember at some point you guys told me it will be implemented soon, in some other issue. 😅 (cc @kdembler)

We put that aside for now

**Comment by drillprop** [comment]
@toiletgranny 
I think I fixed all except `1` from the video and `6`, `7` from NFT. I know that these three were the most important ones, but fixing those will require a lot of work(I'm afraid). We will need to rethink how we manage state and validation in our forms. I created two follow-up issues to cover these problems: https://github.com/Joystream/atlas/issues/2950 https://github.com/Joystream/atlas/issues/2951

**Comment by toiletgranny** [comment]
@drillprop It's such a shame we can't address validation issues now, but I understand we have other priorities right now, so it's fine. Thanks a lot for creating a separate issue for that.

Except for the above, all changes seem to be implemented now. There's one point we might have overlooked, and it's number 7 from the Video workspace:
> Discarding changes in the video information in the Edit mode doesn't trigger the Alert dialog. It should. [Please, see the designs.](https://www.figma.com/file/xm6vBdSnQDroc57rGfGtPM/Video-workspace?node-id=3165%3A165937)

**Comment by drillprop** [comment]
> @drillprop It's such a shame we can't address validation issues now, but I understand we have other priorities right now, so it's fine. Thanks a lot for creating a separate issue for that.
> 
> Except for the above, all changes seem to be implemented now. There's one point we might have overlooked, and it's number 7 from the Video workspace:
> 
> > Discarding changes in the video information in the Edit mode doesn't trigger the Alert dialog. It should. [Please, see the designs.](https://www.figma.com/file/xm6vBdSnQDroc57rGfGtPM/Video-workspace?node-id=3165%3A165937)

We're showing dialog, but you need to click cancel two times 😅 Again this is the same bug as described here: #2950 and I really don't want to deal with it right now.

**Review by toiletgranny — APPROVED** [review]
Oh, okay! Well, in this case, I guess there's nothing else left to do for me other than approve this PR!

**Review by eldiegod — APPROVED** [review]
LGTM besides the mentioned followups

**Pull request merged**
