### PR TITLE
implement figma import for illustrations

### PR DESCRIPTION
**Pull request by rafalpawlow**
While doing another task, @toiletgranny came up with the idea that we could do an figma import for illustrations. So here it is.

### CODE REVIEW

**Review by kdembler — CHANGES_REQUESTED** [review]
This imports a lot of illustrations that we won't be using in our codebase, I wouldn't want dead code to be laying around. I think we need to somehow restrict it to only illustration that Atlas is using

**Comment by rafalpawlow** [comment]
@toiletgranny could you remove unsused illustrations from figma file?

**Comment by toiletgranny** [comment]
@rafalpawlow done!

**Review by kdembler — CHANGES_REQUESTED** [review]
@rafalpawlow Generated illustrations still include some unnecessary ones

**Review by kdembler — APPROVED** [review]

**Pull request merged**
