### PR TITLE
Correct buttons on expired auction - Nft widget

### PR DESCRIPTION
**Pull request by eldiegod**
fixes: #2432

test at: `/video/10`

### CODE REVIEW

**Comment by rafalpawlow** [comment]
@eldiegod this PR needs rebase

**Comment by eldiegod** [comment]
@rafalpawlow done!

**Review by rafalpawlow — CHANGES_REQUESTED** [review]
Generally works well, however during loading `Place a bid` button is visible and it's actually clickable.

https://user-images.githubusercontent.com/13706246/163243415-4ef038d6-d1d2-4a4c-b1f2-c8843b43cfbe.mov

**Comment by eldiegod** [comment]
@kdembler more problems with the timers loading, why don't we just wait till everything loads to show the widget? or alternatively have a `currentBlock` field in the payloads that we can compare with so we can at least know the initial state of the auction before timers kick in

**Comment by kdembler** [comment]
> or alternatively have a currentBlock field in the payloads that we can compare with so we can at least know the initial state of the auction before timers kick in

I would love that, but it's not really feasible at this point, we gotta work with what we have :( Can we just not show any buttons until the timers are finished loading?

**Comment by eldiegod** [comment]
Pushed the fix to not show buttons until timers load

**Review by kdembler — APPROVED** [review]

**Pull request merged**
