### PR TITLE
Update TopbarStudio and other minor tweaks

### LINKED ISSUE #2038: Use new member/channel indicator in studio topbar
We currently have:
Screenshot 2022-01-31 at 16 11 17
 
We should have:
Screenshot 2022-01-31 at 16 12 29

### LINKED ISSUE #2066: Duplicated loader
**Describe the bug**

When you try to log in, 2 loaders appear

**To Reproduce**

1. go to studio
2. logout (remove localStorage entry)
3. refresh page
4. sign in

**Expected behavior**

**Screenshots**
Zrzut ekranu 2022-02-3 o 17 05 45 (2)

**Device (please complete the following information):**

- OS: macOS Monterey 12.1
- Browser Chrome 97.0.4692.99

### PR DESCRIPTION
**Pull request by drillprop**
fix #2038 and #2066
Designs: https://www.figma.com/file/Pf31tuYpozYmpq163U2ho8/Web-Components?node-id=3173%3A135756

### CODE REVIEW

**Comment by eldiegod** [comment]
top bar looks good but not sure whats in scope here

**Comment by drillprop** [comment]
> top bar looks good but not sure whats in scope here

hmm, I thought that it was self-explanatory 😄 . Look at the issue.  
image

Anyway, the scope of this task was just to update the topbar in the studio. 
I didn't add the button with notifications though, because we currently don't have this feature available.

**Review by eldiegod — CHANGES_REQUESTED** [review]
Alright, looks and works well overall, just one thing, I don't think it was reflected in the designs but it triggers me a bit that when there are 2 Avatars and I want to click to open the dropdown they hover individually. 

I think these should hover at the same time and behave like a unit in there because they essentially are, wdyt?

**Comment by drillprop** [comment]
> Alright, looks and works well overall, just one thing, I don't think it was reflected in the designs but it triggers me a bit that when there are 2 Avatars and I want to click to open the dropdown they hover individually.
> 
> I think these should hover at the same time and behave like a unit in there because they essentially are, wdyt?

Or maybe when you click channel avatar we should navigate to user channel? I will ask designers about this because I'm not sure what we should do in this case. The design doesn't explain that at all.
Anyway, good point!

**Comment by drillprop** [comment]
@eldiegod I've talked to Adam, and he agrees with you. I'll implement what you proposed. Updated design: https://www.figma.com/file/Pf31tuYpozYmpq163U2ho8/Web-Components?node-id=4735%3A139148

**Comment by drillprop** [comment]
Updated

**Review by eldiegod — APPROVED** [review]

**Pull request merged**
