### PR TITLE
Playlist thumbnail changes

### PR DESCRIPTION
**Pull request by eldiegod**
Fixes: #2125

### CODE REVIEW

**Review by rafalpawlow — CHANGES_REQUESTED** [review]
When I hover playlist thumbnail, there is wrong overlay
Zrzut ekranu 2022-06-2 o 12 23 40
Zrzut ekranu 2022-06-2 o 12 23 44

Also you have eslint error

**Comment by eldiegod** [comment]
> When I hover playlist thumbnail, there is wrong overlay Zrzut ekranu 2022-06-2 o 12 23 40 Zrzut ekranu 2022-06-2 o 12 23 44
> 
> Also you have eslint error

@rafalpawlow Not sure how you got to that hover state, how do I reproduce? but maybe is not there anymore

**Comment by rafalpawlow** [comment]
@eldiegod it's still there
1. go to storybook
2. switch type to `playlist`
3. hover video thumbnail

Also, shouldn't we add type prop to the VideoTile itself?

**Review by rafalpawlow — CHANGES_REQUESTED** [review]
I think this slot shouldn't be under overlay
Zrzut ekranu 2022-06-3 o 11 18 16

**Review by toiletgranny — CHANGES_REQUESTED** [review]
This looks so slick! ❤️

1. The hover animation appears to be a bit jagged. If you set the animation speed to 10% in Chrome dev tools, you can observe that the thumbnail jumps up by a few pixels imidietaly after hovering. As a result, the actual transition animation starts from there. Can we fix that? Let me know if you prefer to discuss this over a Slack call.
2. I love how you approached the blue cascading sheets animation. A bit differently than what we did in Figma, but heck yeah — I like your version a lot better. I would suggest, however, dropping the opacity animation (or, in other words, setting the background in the initial state, rather than on hover). Also, maybe we could do the same thing to the width (example: `    width: calc(100% - 48px)`): instead of altering it on the hover state, let's have it applied right from the start.
3. There's something unpleasant about how the initial thumbnail content morphs into the full-covered "Play all videos" state, would you agree? Could we try leaving that part without the animation, just to see if it's any better? Feel free to ping me on Slack when you have it ready, I don't think we need to wait for another PR to evaluate this together.
4. When pressing the thumbnail, the very bottom blue sheet doesn't hide. Can we fix that?

### Semi-related
1. Not sure why haven't we noticed that earlier, but all `Thumbnail` components in Storybook come with the wrong variants of `Pill` components. Instead of being of the Medium size (24px of height) and "Overlay" background, they're used in their "Small" sizes (20px of height), and with the opaque background. Weirdly enough, `Pill` components used in the `VideoTile` are correct. Should we worry about that? Would that be too much of a hustle to fix that in the representation of the `Thumbnail` component?
3. One clever thing we did recently with @drillprop to improve accessibility in Atlas by 1%, was applying the same staying we were using in its `"hover` state, to the `:focus-visible` state of the Switch component. Do you reckon we could do the same with Thumbnail components? For both playlists and the regular types?

**Review by toiletgranny — APPROVED** [review]

**Review by rafalpawlow — COMMENTED** [review]
Everything looks good now, but I would like to check it one more after rebase

**Review by rafalpawlow — APPROVED** [review]

**Pull request merged**
