### PR TITLE
🍎 Public channel balance

### PR DESCRIPTION
**Pull request by WRadoslaw**
#2981

### CODE REVIEW

**Comment by dmtrjsg** [comment]
With Kuba earlier we agreed to show a joy tooltip when hovering over the JOY icon. For this to take effect component update in Figma is required. I think we should not wait for this and ship as-is and update the icon later as enhancement. 

For the time being the only currency is JOY so it should be understandable.. Becomes more of an issue when CRTs are out so let's release as built 👍

**Review by drillprop — CHANGES_REQUESTED** [review]
It's not working when you're not signed up. Channel balance is always 0 until you login. Tested on `channel/90`

**Review by drillprop — DISMISSED** [review]
Now it works, but on the other hand, the storybook build is not working. Can we investigate why? Do we want to merge the PR, which will break the storybook?

**Comment by drillprop** [comment]
@attemka could you redeploy this and check if this is a one-off case?

**Review by attemka — APPROVED** [review]

**Pull request merged**
