### PR TITLE
fix overflowing video description

### PR DESCRIPTION
**Pull request by eldiegod**
fixes: #2137

Testable at: https://atlas-au0i7b7oe-joystream.vercel.app/video/18

### CODE REVIEW

**Comment by lcoenengithub** [comment]
lgtm

**Review by lcoenengithub — APPROVED** [review]
lgtm

**Review by kdembler — CHANGES_REQUESTED** [review]
Unfortunately the issue still exists for just regular text that overflows. You can see it here: https://atlas-au0i7b7oe-joystream.vercel.app/video/91 We certainly need `overflow: hidden` for the description container

Test 2022-03-03 at 17 37 14

**Comment by eldiegod** [comment]
> ertainly need `overflow: hidden` for the description container

I think overflow hidden might be a bad idea coz we might miss bugs and description can be cut out

**Review by kdembler — APPROVED** [review]

**Pull request merged**
