### PR TITLE
Playlist widget

### LINKED ISSUE #2253: CW: Playlist Widget
### Context

Playlists content viewer side

⚠️  When user enters the Video page by clicking Playlist tile or from Playlist details page, we display Playlist content component on the right side.

### Scope

- [ ] Playlist widget

> Playlist title
> Channel owner name
> Ordinal number of video playing 
> List of other videos  
> Collapsible state tbc

- [ ] Copy link as all cases are covered here #2251 

Out of scope:
- [ ] Videos play in a defined order (e.g if video 3 plays, video 4 is next)

### Designs

[Figma> ](https://www.figma.com/file/sMydmZJlzhK91FTIPOd7D2/Video-page?node-id=1987%3A128637)

Preview:
Screenshot 2022-03-09 at 16 56 36

### PR DESCRIPTION
**Pull request by drillprop**
Fix #2253 
Design: https://www.figma.com/file/sMydmZJlzhK91FTIPOd7D2/Video-page?node-id=2077%3A114499&t=twcCiv37ZjlMxiig-4

### CODE REVIEW

**Comment by drillprop** [comment]
converted to draft, not ready yet - noticed a few bugs

**Review by WRadoslaw — COMMENTED** [review]
The code looks good, but I think the whole list item inside the widget should be clickable, same as in the YT playlist, rn looks like one has to either click the title or the thumbnail.

**Comment by drillprop** [comment]
> The code looks good, but I think the whole list item inside the widget should be clickable, same as in the YT playlist, rn looks like one has to either click the title or the thumbnail.

fixed

**Review by WRadoslaw — APPROVED** [review]
LGTM

**Pull request merged**
