### PR TITLE
 Split providers & hooks 

### PR DESCRIPTION
**Pull request by eldiegod**
#788

### CODE REVIEW

**Comment by eldiegod** [comment]
Not sure I got this 100% as we wanted it to, u let me know if I missed something @kdembler

**Review by kdembler — COMMENTED** [review]
I think we can improve upon this a bit. My ideas:
1. Let's clean up the structure of `providers` a bit more:
  a) if the provider occupies a single file, let's make sure it doesn't have its own directory (we have some directories with just `index.ts` and the file)
  b) if the single file would be too long/too hard to read, let's split those into `provider.ts` `hook.ts` `types.ts`, etc, based on whatever is needed for this specific provider
  c) let's name providers accordingly to their purpose and not the hook name, for example `providers/useDialog` -> `providers/dialogs`
2. Let's keep `index.ts` inside `providers/`
3. Let's not export provider hooks from `hooks/`. `hooks/` should only export non-provider hooks (the ones defined in `hooks/`)

What do you think about those?

**Comment by eldiegod** [comment]
Yep, made the fixes from the comment as I saw fit pretty much

**Comment by eldiegod** [comment]
@kdembler lets try to merge this one soonish before it gets another million conflicts

**Review by kdembler — APPROVED** [review]

**Pull request merged**
