### PR TITLE
Fix studio auth redirections

### LINKED ISSUE #1586: Logged out user error
When user is not logged in and tries go to `/studio/videos` a meaningless error appear
Zrzut ekranu 2021-11-12 o 12 52 31

Maybe instead of this we could show user some information that she/he should log in or automatically redirect her/him to `/studio`
@kdembler WDYT?

### PR DESCRIPTION
**Pull request by rafalpawlow**
Fixes #1586

### CODE REVIEW

**Comment by eldiegod** [comment]
Pls, add to the description the issue this PR is for

**Comment by rafalpawlow** [comment]
@eldiegod Sorry, I added link to issue

**Review by eldiegod — APPROVED** [review]
Not a fan of having private route nested inside route but this works and before it didn't so 🤷‍♂️

**Comment by rafalpawlow** [comment]
@eldiegod I know but this is consistent with the `react-router` documentation

**Pull request merged**
