### PR TITLE
Center node connection indicator

### PR DESCRIPTION
**Pull request by eldiegod**
fixes: #1776

### CODE REVIEW

**Review by rafalpawlow — CHANGES_REQUESTED** [review]
It's still not centered. Shouldn't we get rid of this margin?
Zrzut ekranu 2021-12-17 o 14 17 19
Zrzut ekranu 2021-12-17 o 14 17 56

**Comment by eldiegod** [comment]
> It's still not centered. Shouldn't we get rid of this margin? Zrzut ekranu 2021-12-17 o 14 17 19 Zrzut ekranu 2021-12-17 o 14 17 56

No, it just needed to be conditionally applied

**Review by rafalpawlow — CHANGES_REQUESTED** [review]
Now content has no padding for side nav
Zrzut ekranu 2021-12-20 o 18 55 12

**Comment by eldiegod** [comment]
That didnt work out too well so tried a diff approach

**Review by rafalpawlow — APPROVED** [review]
Looks good now!

**Pull request merged**
