### PR TITLE
Uploads view video titles fix

### PR DESCRIPTION
**Pull request by mikkio-j**
video titles didn't show up before in uploads view

### CODE REVIEW

**Comment by drillprop** [comment]
Generally, it works. There is still a small issue - when you upload the video and then go to `/uploads` the title will appear on the bar after a small delay. It seems it doesn't happen when you are on `/uploads` path.

**Comment by mikkio-j** [comment]
> Generally, it works. There is still a small issue - when you upload the video and then go to `/uploads` the title will appear on the bar after a small delay. It seems it doesn't happen when you are on `/uploads` path.

Couldn't really resolve that issue, @kdembler - will appreciate some guidance here 😃

**Comment by mikkio-j** [comment]
@kdembler @drillprop pushed fix. Turned out hook didn't fetch **all** videos on initial fetch, added `id_in` for fetching videos that are present in `uploadsState`. No need for additional useEffect. Should be good now, let me know if otherwise

**Comment by drillprop** [comment]
yep. I think you fixed the issue. Works for me 👍🏻

**Review by drillprop — APPROVED** [review]

**Review by kdembler — APPROVED** [review]

**Pull request merged**
