### PR TITLE
Not found page follow up

### PR DESCRIPTION
**Pull request by eldiegod**

### CODE REVIEW

**Comment by eldiegod** [comment]
@TCzechowski could you check the not found page and let me know if you spot any issues?

**Review by rafalpawlow — CHANGES_REQUESTED** [review]
One more thing from my side. Let's use pattern from figma api

**Review by TCzechowski — APPROVED** [review]
The content is now centered both vertically and horizontally, and I didn't see any other issues previously, so I think we are good to go! :)

**Comment by kdembler** [comment]
Agreed with @rafalpawlow here, let's use illustrations synced via Figma API

**Comment by eldiegod** [comment]
> Agreed with @rafalpawlow here, let's use illustrations synced via Figma API

@rafalpawlow how do I do that again?

**Comment by rafalpawlow** [comment]
@eldiegod just run `yarn svgs:illustrations`

**Review by rafalpawlow — APPROVED** [review]

**Pull request merged**
