### PR TITLE
fix overflowing video title

### PR DESCRIPTION
**Pull request by kdembler**
Screenshot 2021-08-30 at 11 40 10

### CODE REVIEW

**Review by drillprop — APPROVED** [review]

**Comment by kdembler** [comment]
hmm it still breaks when the tile is the last one in the row
Screenshot 2021-08-30 at 12 43 19

**Comment by drillprop** [comment]
Good catch, didn't notice that at all. Also, it seems that it's not happening on certain viewports

https://user-images.githubusercontent.com/51168865/131329477-c8b8be6a-da69-4d67-9003-609e7b43a977.mov

**Comment by kdembler** [comment]
Yep, it was because of the `maxColumnCss` style, should be fixed now

**Review by drillprop — APPROVED** [review]
Works fine now 👍🏻

**Pull request merged**
