### PR TITLE
❎ Negative balance

### PR DESCRIPTION
**Pull request by WRadoslaw**
#3622

### CODE REVIEW

**Review by drillprop — CHANGES_REQUESTED** [review]
1. image

The total is not correct in this case? 
Actually, if I understand this correctly: 
- The invitation lock should be constant. So it should be always 100 000 in my case in the screenshot above(this is the value that is given by the faucet)?
- Total balance should be locked invitational + transferable balance. 

But please confirm this with Dima, I'm a little confused about what should we show here. 

2. You forgot to add information about the negative balance: 
image

**Comment by dmtrjsg** [comment]
1️⃣ 
Keep the label as  "Locked Funds". That field should only display the locked funds that can be spent on tx fees. 

Update tooltip to "Your transferable balance is negative because the channel creation bond was paid from it while it was 0. You can still upload videos and perform other actions, but the transaction fees will be covered by the invitation lock as part of your locked funds, and it cannot be transferred."

2️⃣ ⚠️ Check why the transferable balance gets reduced with every tx signed, like "Like", Comment and reaction to the video. The only part that needs to be paid from transferable balance when it is <= 0 is the bloat bonds, which are taken for channel creation and (maybe) a comment.

**Comment by WRadoslaw** [comment]
About

> 1️⃣ Keep the label as "Locked Funds". That field should only display the locked funds that can be spent on tx fees.
> 
> Update tooltip to "Your transferable balance is negative because the channel creation bond was paid from it while it was 0. You can still upload videos and perform other actions, but the transaction fees will be covered by the invitation lock as part of your locked funds, and it cannot be transferred."
> 
> 2️⃣ ⚠️ Check why the transferable balance gets reduced with every tx signed, like "Like", Comment and reaction to the video. The only part that needs to be paid from transferable balance when it is <= 0 is the bloat bonds, which are taken for channel creation and (maybe) a comment.

About the 2nd point. 

Right now it looks like the transferable balance should be going down with each TX fee paid. Since Invitation lock works like a debt, it means that every token spend from lock will need to be paid back. 
Eg. 
My inv lock - 100 // Balance 0
I've spent for fees - 20 // Balance - 20
My friend sent me - 30 // Balance - 10

**Comment by dmtrjsg** [comment]
Solution: 
1. We _show_ transferable balance at 0 all the time. 
2. When transferable balance goes to negative zone, we display tooltip
3. Tooltip has one balance only "Spendable balance". Spendable balance = Invitation lock - debt on transferble balance. 
4. We remove "invitation lock" and total balance from the tooltip. 
5. Tooltip text says: "You don't have any tokens to spend on NFTs or transfer, but there is a balance you can spend on paying of transaction fees for creating channels, posting videos, adding comments and reactions. This balance needs to be repaid before accumulating transferable balance."

**Review by drillprop — CHANGES_REQUESTED** [review]
I see a tooltip in the account where is a transferable balance, and I think I shouldn't. 
image


I tested this on mainnet environment with account
`j4X5B4Dsgeb43yzpC8PbxSodaS7G3uYxNZbRs1fW9UNEYKfp3`
 This is my balance on pioneer. I don't have an invitation lock on this account, only a vesting lock
image

**Review by drillprop — APPROVED** [review]
LGTM but Let's wait for final approval from @dmtrjsg

**Comment by dmtrjsg** [comment]
pls don't get mad at me 😬  but after a final review I feel that to effectively solve the problem of informing the users on why they receive less JOY from NFT sale or transfer we need to: 

1. Also show tooltip when transferable balance = 0. And invitation lock is not spent.  (currently tooltip shows only when lock balance is spent on at least one transaction).
2. Display transferable balance and joy token icon in red, when transferable balance is non-positive.  
3. Slightly update copy to "Your transferable balance is zero, meaning you cannot buy NFTs or transfer tokens. There is a spendable balance from faucet, which you can still spend on paying transaction fees for creating channels, posting videos, adding comments and reactions. This balance needs to be repaid before accumulating transferable balance."

cc @WRadoslaw @drillprop

**Comment by dmtrjsg** [comment]
Perfect, thanks a mil @WRadoslaw and @attemka 🙏

**Pull request merged**
