### PR TITLE
View history of comment edits

### LINKED ISSUE #2441: View History of Edits
View edit history of comments [link](https://www.figma.com/file/sMydmZJlzhK91FTIPOd7D2/Video-page?node-id=2213%3A140609)

`isEdited` will be available directly on the `Comment`, history will need fetching via separate query

### PR DESCRIPTION
**Pull request by drillprop**
Fix #2441 
~This is created based on https://github.com/Joystream/atlas/pull/2526~
~I'll rebase once it's merged.~ 

Be aware, that I didn't add any styling to the edit history dialog, I think after the [Dialog update](https://github.com/Joystream/atlas/pull/2462) this won't be needed. 

You can test the full flow on the video with id "1" and you can check the CommentSnaphsot component in the storybook.

Designs
Flow: https://www.figma.com/file/sMydmZJlzhK91FTIPOd7D2/Video-page?node-id=2213%3A140609
Component: 
https://www.figma.com/file/sMydmZJlzhK91FTIPOd7D2/Video-page?node-id=2429%3A220249

### CODE REVIEW

**Review by rafalpawlow — CHANGES_REQUESTED** [review]
Looks good, I found one small glitch
Zrzut ekranu 2022-05-4 o 15 45 01

**Comment by kdembler** [comment]
Please make sure we also can see the original comment body

**Comment by drillprop** [comment]
> Please make sure we also can see the original comment body

It looks like this is a QN issue. I basically cannot get the original comment. Tried querying events and comments queries, and I get only edited entries. You can check the comment with id  "METAPROTOCOL-OLYMPIA-199868-2" on the video with id "2".

**Comment by drillprop** [comment]
> Please make sure we also can see the original comment body

Should be fixed. Thanks for the tip with `commentCreatedEvent`

**Review by toiletgranny — CHANGES_REQUESTED** [review]
Very nice! The only thing left to adjust is the width of the Edit history dialog, which should be set to `768px`.

**Review by toiletgranny — APPROVED** [review]

**Review by rafalpawlow — APPROVED** [review]

**Pull request merged**
